In [2]:
import numpy as np

In [33]:
class RidgeRegression(object):
    def __init__(self, lmbda=0.1):
        self.lmbda = lmbda

    def fit(self, X, y):
        C = X.T.dot(X) + self.lmbda*np.eye(X.shape[1])
        self.w = np.linalg.inv(C).dot(X.T.dot(y))

    def predict(self, X):
        return X.dot(self.w)

    def get_params(self, deep=True):
        return {"lmbda": self.lmbda}

    def set_params(self, lmbda=0.1):
        self.lmbda = lmbda
        return self

In [46]:
import pandas as pd
train_data = pd.read_csv('./1-prostate-training.csv', header=None)
train_data.head(10)

0         1   2         3  4         5  6   7         8
0  1.665114  4.237778  64  2.073879  0 -1.387068  6   0  2.677591
1  0.269401  4.080930  65  1.960846  0 -0.792294  6   0  1.924249
2  3.825840  3.888853  44 -1.382499  1  2.183515  7  40  4.684443
3 -0.424693  3.513333  70  1.249222  0 -0.595768  7  30  1.470176
4  2.514151  3.467340  57  0.428525  0  2.318480  7  60  3.530763
5  0.288686  4.095910  65  1.960449  0 -0.806823  6   0  1.924249
6 -0.381821  3.504987  70  1.246730  0 -0.596905  7  30  1.470176
7 -1.046399  3.221741  50 -1.373105  0 -1.379131  6   0  0.765468
8  1.575711  3.739431  60  1.693815  0  0.824897  7  30  3.587677
9  1.664291  3.394136  61  0.622534  0 -1.376971  7  15  2.553344

In [19]:
test_data = pd.read_csv('./1-prostate-test-Vi-Du.csv', header=None)
test_data

0         1   2         3  4         5  6   7  8
0 -0.981850  2.169459  51 -1.629436  0 -1.386294  6   0  0
1 -0.994252  3.319626  58 -1.386294  0 -1.386294  6   0  0
2  1.250000  2.691243  74 -1.386294  0 -1.386294  7  20  0
3 -1.203973  3.282789  58 -1.386294  0 -1.386294  6   0  0
4  0.751416  3.432373  62 -1.629436  0 -1.386294  6   0  0
5 -1.982212  3.228826  50 -1.386294  0 -1.386294  6   0  0
6  0.693147  3.539509  58  1.368672  0 -1.386294  6   0  0
7  0.264222  3.613800  65 -1.386294  0 -1.386294  6   0  0
8 -1.347074  3.598681  63  1.266948  0 -1.386294  6   0  0
9  0.751416  3.432373  62 -1.629436  0 -1.386294  6   0  0

In [50]:
ridreg = RidgeRegression(0.2)
ridreg.fit(train_data.values[:,:8], train_data.values[:,8:9])
ridreg.w

array([[ 0.57816607],
       [ 0.57985956],
       [-0.01205774],
       [ 0.15261331],
       [ 0.85165891],
       [-0.24030755],
       [-0.01811218],
       [ 0.00958611]])

In [51]:
ridreg.predict(train_data.values[:,:8])

array([[3.18948458],
       [2.11934348],
       [4.30903364],
       [1.4422678 ],
       [2.73350697],
       [2.14261057],
       [1.46210826],
       [0.67346578],
       [2.57697102],
       [2.63774619],
       [2.12546707],
       [1.84659943],
       [2.1339285 ],
       [1.58932545],
       [3.51586935],
       [3.17377011],
       [2.59633846],
       [1.4663524 ],
       [2.48475606],
       [3.84547587],
       [2.39377715],
       [4.31413895],
       [1.68852712],
       [2.72988601],
       [2.02939876],
       [2.21702923],
       [1.70716679],
       [3.45525628],
       [2.18465174],
       [3.3464754 ],
       [2.24294515],
       [1.87260809],
       [2.46593356],
       [3.18777795],
       [2.39485862],
       [2.29658924],
       [4.05546248],
       [1.95208133],
       [3.82814092],
       [2.40184952],
       [2.50043131],
       [2.92029727],
       [3.10849622],
       [0.69032447],
       [3.12783356],
       [3.10802424],
       [1.46272294],
       [2.935

array([[ 2.677591 ],
       [ 1.9242487],
       [ 4.6844434],
       [ 1.4701758],
       [ 3.5307626],
       [ 1.9242487],
       [ 1.4701758],
       [ 0.7654678],
       [ 3.5876769],
       [ 2.5533438],
       [ 1.9242487],
       [ 1.8946169],
       [ 1.9242487],
       [ 2.1575593],
       [ 3.3928291],
       [ 2.9626924],
       [ 2.6567569],
       [ 1.2669476],
       [ 2.5217206],
       [ 4.3851468],
       [ 3.0373539],
       [ 4.6844434],
       [ 0.3715636],
       [ 3.5307626],
       [ 1.2669476],
       [ 0.8544153],
       [ 0.3715636],
       [ 4.029806 ],
       [ 2.2975726],
       [ 3.4578927],
       [ 1.4929041],
       [ 1.446919 ],
       [ 2.5217206],
       [ 2.9626924],
       [ 3.0373539],
       [ 2.7942279],
       [ 3.9843437],
       [ 1.6389967],
       [ 4.3851468],
       [ 3.0373539],
       [ 1.7137979],
       [ 3.7123518],
       [ 3.6800909],
       [-0.4307829],
       [ 3.6800909],
       [ 3.6800909],
       [ 1.2669476],
       [ 2.85